name: Release

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
# https://github.com/marketplace/actions/goreleaser-action#run-on-new-tag
on:
  release:
    types: [published]

permissions:
  contents: write # GoReleaser
  packages: write # Docker

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Check out unixODBC
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: lurcher/unixODBC
          ref: v2.3.14 # https://github.com/lurcher/unixODBC/releases
          path: unixODBC
      - name: Build release image
        run: docker build -t custom-goreleaser-cross -f Dockerfile.release .
      - name: Clean up unixODBC source
        run: rm -rf unixODBC

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm -e GITHUB_TOKEN \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD":"$PWD" -w "$PWD" \
            custom-goreleaser-cross \
            release --clean

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.package
          context: .
          push: true
          sbom: false
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
